-- PostgreSQL Database Schema for NPC Reporting System
-- This schema is auto-generated by Django migrations, but provided here for reference

-- Plants table
CREATE TABLE plants (
    id BIGSERIAL PRIMARY KEY,
    code VARCHAR(10) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    capacity_mw DECIMAL(10, 2) NOT NULL,
    location VARCHAR(200) NOT NULL,
    commissioned_date DATE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_plants_code ON plants(code);
CREATE INDEX idx_plants_is_active ON plants(is_active);

-- Units table
CREATE TABLE units (
    id BIGSERIAL PRIMARY KEY,
    plant_id BIGINT NOT NULL REFERENCES plants(id) ON DELETE CASCADE,
    unit_number INTEGER NOT NULL CHECK (unit_number >= 1),
    capacity_mw DECIMAL(10, 2) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    commissioned_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(plant_id, unit_number)
);

CREATE INDEX idx_units_plant_unit ON units(plant_id, unit_number);
CREATE INDEX idx_units_is_active ON units(is_active);

-- Uploaded files table (audit trail)
CREATE TABLE uploaded_files (
    id BIGSERIAL PRIMARY KEY,
    file VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    plant_id BIGINT NOT NULL REFERENCES plants(id) ON DELETE CASCADE,
    uploaded_by_id INTEGER REFERENCES auth_user(id) ON DELETE SET NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) DEFAULT 'PENDING',
    records_imported INTEGER DEFAULT 0,
    error_message TEXT,
    file_size INTEGER NOT NULL,
    checksum VARCHAR(64) NOT NULL
);

CREATE INDEX idx_uploaded_files_plant_date ON uploaded_files(plant_id, uploaded_at);
CREATE INDEX idx_uploaded_files_status ON uploaded_files(status);
CREATE INDEX idx_uploaded_files_user ON uploaded_files(uploaded_by_id);

-- Generation reports table
CREATE TABLE generation_reports (
    id BIGSERIAL PRIMARY KEY,
    plant_id BIGINT NOT NULL REFERENCES plants(id) ON DELETE CASCADE,
    unit_id BIGINT NOT NULL REFERENCES units(id) ON DELETE CASCADE,
    report_date DATE NOT NULL,
    uploaded_file_id BIGINT NOT NULL REFERENCES uploaded_files(id) ON DELETE CASCADE,
    generation_kwh DECIMAL(15, 2) NOT NULL,
    operating_hours DECIMAL(5, 2) NOT NULL CHECK (operating_hours >= 0 AND operating_hours <= 24),
    availability_hours DECIMAL(5, 2) NOT NULL CHECK (availability_hours >= 0 AND availability_hours <= 24),
    forced_outage_hours DECIMAL(5, 2) DEFAULT 0,
    scheduled_outage_hours DECIMAL(5, 2) DEFAULT 0,
    capacity_factor DECIMAL(5, 2),
    availability_factor DECIMAL(5, 2),
    remarks TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(plant_id, unit_id, report_date)
);

CREATE INDEX idx_generation_reports_plant_date ON generation_reports(plant_id, report_date);
CREATE INDEX idx_generation_reports_date ON generation_reports(report_date);
CREATE INDEX idx_generation_reports_unit_date ON generation_reports(unit_id, report_date);
CREATE INDEX idx_generation_reports_uploaded_file ON generation_reports(uploaded_file_id);

-- Insert initial plant data
INSERT INTO plants (code, name, capacity_mw, location) VALUES
('AGUS1', 'Agus 1 Hydroelectric Plant', 0, 'Lanao del Sur'),
('AGUS2', 'Agus 2 Hydroelectric Plant', 0, 'Lanao del Sur'),
('AGUS4', 'Agus 4 Hydroelectric Plant', 0, 'Lanao del Norte'),
('AGUS5', 'Agus 5 Hydroelectric Plant', 0, 'Lanao del Norte'),
('AGUS6', 'Agus 6 Hydroelectric Plant', 0, 'Lanao del Norte'),
('AGUS7', 'Agus 7 Hydroelectric Plant', 0, 'Lanao del Norte');

-- Note: Update capacity_mw values with actual plant capacities
-- Note: Add units for each plant based on actual configuration
